# Nome do pipeline que será exibido no GitHub Actions
name: Build and deploy Python app to Azure Web App - Aula1004

# Define quando o pipeline será executado
on:
  # Executa quando houver push na branch main
  push:
    branches:
      - main
  # Permite execução manual
  workflow_dispatch:

# Define os jobs do pipeline
jobs:
  # Job de build
  build:
    # Sistema operacional utilizado
    runs-on: ubuntu-latest

    # Permissões necessárias
    permissions:
      contents: read

    # Etapas do build
    steps:
      # Faz checkout do código
      - uses: actions/checkout@v4

      # STEP ADICIONADO (exercício)
      - name: Mensagem inicial
        run: echo "Iniciando o deploy do meu projeto!"

      # Configura o Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      # Cria ambiente virtual e instala dependências
      - name: Create and Start virtual environment and Install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt

      # Faz upload dos arquivos para o deploy
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/

  # Job de deploy
  deploy:
    # Executa após o build
    needs: build

    # Sistema operacional
    runs-on: ubuntu-latest

    # Permissões
    permissions:
      id-token: write
      contents: read

    # Etapas do deploy
    steps:
      # Baixa o artefato
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Login na Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4D8FFC6501254A4584408F8B9B6E5FC2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BBC29FAAED8B45C99B8AD6B322625020 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DFE77667FBDA442EBF34B12EE80BD536 }}

      # Deploy na Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Aula1004'
          slot-name: 'Production'
